version: '3'
services:
  cspace-mongo:
    image: "mongo:3.4"
    ports:
      - "27017:27017"
    volumes:
      - '/data/mongodb:/data/db'
  cspace-redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - '/data/redis:/data'
  cspace-collections-consumer-files:
    build:
      context: ../../../../
      dockerfile: src/cspace/poieventservice/docker/consumer_files.docker
    image: "connectedspace/platform-collections-consumer-files:1.0.0"
    volumes:
      - config-vol:/etc/cspace/consumer.d
  cspace-collections:
    build:
      context: ../../../../
      dockerfile: src/cspace/poieventservice/docker/server.docker
    image: "connectedspace/platform-collections:1.0.2"
    depends_on:
      - "cspace-mongo"
  cspace-collections-consumer:
    build:
      context: ../../../../
      dockerfile: src/cspace/poieventservice/docker/consumer.docker
    image: "connectedspace/platform-collections-consumer:1.0.2"
    depends_on:
      - "cspace-collections"
      - "cspace-collections-consumer-files"
    volumes:
      - config-vol:/etc/cspace/consumer.d
volumes:
  config-vol:
